name: asistence_frontend
description: Frontend en Flutter para la API (login + Google button)
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.0
  http: ^0.13.6
  shared_preferences: ^2.1.1
  flutter_native_splash: ^2.4.7

flutter:
  assets:
    - assets/icons8-logo-de-google-48.png
    - assets/logo_asistenciaiiap.png
    - assets/splash_asistenciaiiap.png
    - assets/transparent.png
    - assets/logo_padded.png
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_asistenciaiiap.png"

flutter_native_splash:
  color: "#121212"
  image: assets/logo_asistenciaiiap.png

  android_12:
    image: assets/logo_asistenciaiiap.png
    color: "#121212"

  fullscreen: true